# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'piscineDay07V3' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for piscineDay07V3
	pod "Alamofire", "~> 4.9.0"
	pod "ForecastIO"
	pod "RecastAI"
	


end
